version: '3.8'

# テスト・開発用の軽量Docker Compose設定
services:
  # PostgreSQL データベース（軽量設定）
  postgres:
    image: postgres:15
    container_name: readscape_postgres_test
    environment:
      POSTGRES_DB: readscape
      POSTGRES_USER: readscape_user
      POSTGRES_PASSWORD: readscape_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./infrastructure/config/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U readscape_user -d readscape"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - readscape_test_network

  # Redis キャッシュ（軽量設定）
  redis:
    image: redis:7-alpine
    container_name: readscape_redis_test
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - readscape_test_network

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  readscape_test_network:
    driver: bridge