spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:50}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: 20000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    show-sql: false
  
  # Redis Configuration (本番環境)
  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      connect-timeout: 2000ms
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: -1ms
      ssl: ${REDIS_SSL:false}
  
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:3600000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}

server:
  error:
    include-stacktrace: never
  # HTTPS設定（本番環境推奨）
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE_PATH:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: PKCS12
    key-alias: readscape
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: WARN
    jp.readscape: INFO
  file:
    name: /var/log/readscape/${APP_NAME}.log
    max-size: 100MB
    max-history: 30

# OpenAPI Documentation (本番環境では無効化)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false