spring:
  application:
    name: readscape-consumer-api
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:readscape}
    username: ${DB_USER:readscape_user}
    password: ${DB_PASSWORD:readscape_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Tokyo
  
  flyway:
    enabled: true
    schemas: readscape
    locations: filesystem:../infrastructure/database/migrations
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:docker-development-jwt-secret-key-256-bits-long-for-secure-authentication}
      expiration: 3600000  # 1時間（ミリ秒）
      refresh-expiration: 2592000000  # 30日（ミリ秒）

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    jp.readscape.consumer: INFO
    org.springframework.security: WARN
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html