spring:
  application:
    name: readscape-consumer-api
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:50}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: 20000
      validation-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: Asia/Tokyo
  
  flyway:
    enabled: true
    schemas: readscape
    locations: filesystem:../infrastructure/database/migrations
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
  
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:3600000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always
  # HTTPS設定（オプション）
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE_PATH:}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:}
    key-store-type: PKCS12
    key-alias: readscape

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}

logging:
  level:
    root: ${LOG_LEVEL:WARN}
    jp.readscape.consumer: INFO
    org.springframework.security: WARN
    org.flywaydb: WARN
  file:
    name: /var/log/readscape/readscape-consumer-api.log

# OpenAPI Documentation (本番では無効化推奨)
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}